#mySQL
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://travelgo-mysql.cm0q6xl9l1ab.ap-northeast-2.rds.amazonaws.com:3306/travelgo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root0310
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    path-match:
      matching-strategy : ant_path_matcher

#Swagger
springdoc:
  info:
    title: TravelGo API 문서
    description: TravelGo API 연동 문서
    version: 0.0.1